[build]
  functions = "functions"  # Path to your serverless functions
  publish = "public"       # Path to your static site (public folder)

[[redirects]]
  from = "/images"
  to = "/.netlify/functions/getImages"
  status = 200

[[functions]]
  included_files = ["functions/gallery/**"]